version: "3.4"

services:
  rabbitmq:
      container_name: "rabbitmq"
      image: rabbitmq:3.8-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
      ports:
          # AMQP protocol port
          - '5672:5672'
          # HTTP management UI
          - '25672:15672'

  eventstore.db:
    container_name: "eventstore-brewup"
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: brewup-data
        target: /var/lib/eventstore-brewup
      - type: volume
        source: brewup-logs
        target: /var/log/eventstore-brewup

  brewup-mongodb:
        image: mongo
        ports:
            - 27017:27017

        volumes:
          - type: volume
            source: brewup-mongodb-data
            target: /var/lib/brewup-mongodb

volumes:
  brewup-data:
  brewup-logs:
  brewup-mongodb-data: